// build_background.mjs — builds a film-style background: many shots that MOVE,
// cut every ~5s. For each segment it downloads real footage from Pexels (it truly moves);
// if none is available, it generates an AI image and animates it with zoompan (real motion). Then
// concatenates everything into bg/bg.mp4 (fast cuts) for the graphics overlay on top.
//
// Uso: node pipeline/build_background.mjs <timing.json> [outDir=bg] [maxSeconds]
// Env: PEXELS_API_KEY (optional; without it, everything uses animated AI images).
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { TEXT_MODELS } from "./_models.mjs";

const [timingPath, outDir = "bg", maxSecondsArg] = process.argv.slice(2);
const KEY = process.env.PEXELS_API_KEY || "";
const PIXABAY = process.env.PIXABAY_API_KEY || "";
const GEMINI = process.env.GEMINI_API_KEY || "";
const timing = JSON.parse(fs.readFileSync(timingPath, "utf8"));
const maxSeconds = maxSecondsArg && parseFloat(maxSecondsArg) > 0 ? parseFloat(maxSecondsArg) : timing.total;
const total = Math.min(timing.total, maxSeconds);
fs.mkdirSync(outDir, { recursive: true });

// Palancas of the GATE OF QUALITY (auto-mejora): between intentos, the auto-review can
// pedir more punch/brillo/saturacion/contraste or cuts more fast, via env FX_*.
const NUMENV = (v, d) => (v === undefined || v === "" || isNaN(+v) ? d : +v);
const FX_PACE = (process.env.FX_PACE || "").toLowerCase();
const SEG = FX_PACE === "faster" ? 3.6 : 5.0;
const TD = FX_PACE === "faster" ? 0.5 : 0.6; // transition duration (overlap between shots)
const _brt = (0.07 + NUMENV(process.env.FX_BRIGHT, 0)).toFixed(3);
const _sat = (1.02 + NUMENV(process.env.FX_SAT, 0)).toFixed(3);
const _ctr = (1.05 + NUMENV(process.env.FX_CONTRAST, 0)).toFixed(3);
// Grade cinematografico consistente in EVERYTHING shot (footage and images IA): curva
// filmica of contraste + micro-nitidez + vinneta suave. Uploads the "piso" visual of cada
// fotograma (that is lo that califica the auto-review) without depender of the ajustes FX.
// Without vinneta (oscurecia and the IA pedia MORE luz). Curva suave + micro-nitidez.
// Look CINEMATOGRAFICO (sin oscurecer): LUT 3D teal-orange filmico (assets/luts/cinematic.cube,
// generated by make_lut.mjs) + micro-nitidez + GRANO of pelicula temporal. The LUT da the grade
// pro consistente; if by something faltara the file, ffmpeg fallaria -> the background is optional and the
// render sigue. Uploads much the "not-shot" free.
const LUT_PATH = "assets/luts/cinematic.cube";
const CINE = fs.existsSync(LUT_PATH)
  ? `lut3d=${LUT_PATH},unsharp=3:3:0.26,noise=alls=6:allf=t`
  : `curves=preset=lighter,colorbalance=rs=-0.04:bs=0.05:rh=0.05:bh=-0.05,unsharp=3:3:0.28,noise=alls=6:allf=t`;
const VF = `eq=brightness=${_brt}:saturation=${_sat}:contrast=${_ctr},${CINE}`; // grade + cine
// Topics of relleno for VARIAR when dos shots seguidos caerian in the same topic.
const FILLERS = [
  { kw: "money cash counting bright", ai: "close up of cash money bills, bright clean light, cinematic" },
  { kw: "modern city skyline aerial day", ai: "modern city skyline, blue sky, bright daylight, aerial" },
  { kw: "stock market screen data bright", ai: "bright stock market data screen, clean white light" },
  { kw: "modern data center bright", ai: "modern data center, bright clean led light, wide" },
  { kw: "person working laptop office", ai: "person working on a laptop in a bright modern office, daylight" },
  { kw: "gold coins wealth bright", ai: "gold coins and stacks of money, bright clean light, glowing particles" },
];
// Transiciones profesionales de ffmpeg (se van rotando).
const TRANS = ["fade", "dissolve", "smoothleft", "smoothup", "wiperight", "circleopen", "slideup", "radial", "diagtl", "fadegrays"];
// HyperFrames reads bg.mp4 as <video> and advances the frames in order when rendering. to GOP
// ligero (keyframe cada ~1s) da buen seek WITHOUT inflar the file nor frenar the decodificacion
// secuencial. (All-intra -g 1 is probo: files enormes -> more R2 and render more slow; discarded.)
const SEEK_SAFE = "-g 30 -keyint_min 30";

// Topic of cada shot segun lo that dice the voice (footage and prompt IA).
function theme(text) {
  const t = text.toLowerCase();
  const has = (...w) => w.some((x) => t.includes(x));
  if (has("netflix", "hollywood", "movies", "streaming empire")) return { kw: "modern cinema movie theater bright", ai: "modern cinema movie theater, bright screen, clean light" };
  if (has("youtube tv", "television", "cable", "channels")) return { kw: "modern living room television day", ai: "bright modern living room with a large tv, big window, daylight" };
  if (has("ads", "advertising", "election", "campaign")) return { kw: "hand smartphone video app", ai: "close up of a hand holding a smartphone showing a video, bright clean light" };
  if (has("creator", "filming", "camera", "youtuber", "mrbeast", "teenager", "bedroom")) return { kw: "content creator filming studio bright", ai: "young creator filming in a bright home studio with ring light, clean" };
  if (has("subscription", "premium", "eighty-three")) return { kw: "streaming app phone bright", ai: "hand holding phone with a subscribe button, bright clean light" };
  if (has("second", "minute", "clock", "time", "counting")) return { kw: "clock time macro bright", ai: "extreme macro of a watch mechanism and falling coins, bright light" };
  if (has("hundred billion", "rich", "richer", "wealth", "millionaire", "empire", "eighty-five")) return { kw: "stacks of money wealth bright", ai: "towering stacks of cash and gold coins, bright clean light, glowing particles" };
  if (has("money", "dollars", "cash", "billion", "million", "revenue", "earn", "sixty")) return { kw: "money cash falling bright", ai: "flowing river of dollar bills and coins, bright clean light, macro" };
  if (has("google", "machine", "internet", "platform", "data")) return { kw: "modern data center bright", ai: "bright modern data center, clean led light, wide angle" };
  return { kw: "abstract technology money bright", ai: "abstract money and data, bright clean light, glowing particles" };
}

const beats = timing.beats.filter((b) => b.start < total);
const segs = [];
let cur = null;
for (const b of beats) {
  if (!cur) cur = { start: b.start, end: b.end, text: b.text };
  else { cur.end = b.end; cur.text += " " + b.text; }
  if (cur.end - cur.start >= SEG) { segs.push(cur); cur = null; }
}
if (cur) segs.push(cur);
segs.forEach((s) => { s.end = Math.min(s.end, total); });

async function pexelsLink(kw) {
  if (!KEY) return null;
  try {
    const r = await fetch(`https://api.pexels.com/videos/search?query=${encodeURIComponent(kw)}&orientation=landscape&size=large&per_page=15`, { headers: { Authorization: KEY } });
    if (!r.ok) return null;
    const j = await r.json();
    const vids = (j.videos || []).sort(() => Math.random() - 0.5); // variedad
    for (const v of vids) {
      const files = (v.video_files || []).filter((f) => f.file_type === "video/mp4" && f.width);
      files.sort((a, b) => b.width - a.width);
      const f = files.find((f) => f.width >= 1280 && f.width <= 1920) || files[0];
      if (f) return f.link;
    }
  } catch {}
  return null;
}
async function pixabayLink(kw) {
  if (!PIXABAY) return null;
  try {
    const r = await fetch(`https://pixabay.com/api/videos/?key=${PIXABAY}&q=${encodeURIComponent(kw)}&per_page=12`);
    if (!r.ok) return null;
    const j = await r.json();
    const hits = (j.hits || []).sort(() => Math.random() - 0.5);
    for (const h of hits) {
      const v = h.videos || {};
      const f = v.large || v.medium || v.small;
      if (f && f.url) return f.url;
    }
  } catch {}
  return null;
}

// ── FUENTES INFORMATIVAS/HISTORICAS (relevancia real > stock generico) ─────────────
// For segmentos that hablan of a EVENTO/PERSONA/LUGAR/EPOCA real (kind="archival") is
// much best metraje of FILE (Wikimedia / Internet Archive / NASA) that a shot
// generico of money. Cada fetcher is best-effort: try/catch + timeout; if fails or not
// hay licencia usable, devuelve null and the ruteo cae to the siguiente fuente -> NEVER rompe
// the corrida. ONLY is acepta CC0/CC-BY/dominio public (ver sources.seed.JSON); CC-BY
// stores its atribucion for the description of the video.
const UA = { "user-agent": "video-forge/1.0 (educational faceless data channel)" };
const tf = (u, ms = 30000, o = {}) => fetch(u, { ...o, headers: { ...UA, ...(o.headers || {}) }, signal: AbortSignal.timeout(ms) });
const strip = (s) => (s || "").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();

// Descarga acotada: if Content-Length (or the buffer) supera the tope, aborta -> not bajamos
// gigas by a shot of ~5s. With timeout duro (AbortSignal) for not colgar the phase.
async function dlCapped(url, dest, maxBytes = 130 * 1024 * 1024, ms = 150000) {
  const r = await tf(url, ms);
  if (!r.ok) return false;
  const len = +(r.headers.get("content-length") || 0);
  if (len && len > maxBytes) return false;      // demasiado pesado -> ni lo bajamos
  const buf = Buffer.from(await r.arrayBuffer());
  if (buf.length > maxBytes) return false;
  fs.writeFileSync(dest, buf);
  return true;
}

// Wikimedia Commons: biblioteca enorme CC/PD con descarga directa. Busca VIDEOS (.webm/.ogv/.mp4)
// and ACEPTA only if the licencia real of the item is CC0/CC-BY/dominio public (rechaza SA/NC/ND).
async function wikimediaVideo(q) {
  try {
    const api = `https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&generator=search&gsrsearch=${encodeURIComponent(q + " filetype:video")}&gsrnamespace=6&gsrlimit=20&iiprop=url|size|extmetadata`;
    const r = await tf(api, 30000); if (!r.ok) return null;
    const j = await r.json();
    const pages = Object.values((j.query && j.query.pages) || {});
    for (const p of pages) {
      const ii = (p.imageinfo || [])[0]; if (!ii || !ii.url) continue;
      // The url can traer query (?utm_...): probar the extension about the path, without the query.
      // Only formatos of VIDEO (webm/ogv/mp4); .ogg suele ser audio -> fuera.
      if (!/\.(webm|ogv|mp4)$/i.test(ii.url.split("?")[0])) continue;
      const sz = +(ii.size || 0); if (sz < 1e6 || sz > 120e6) continue; // ni miniaturas ni archivos gigantes
      const em = ii.extmetadata || {};
      const licName = (em.LicenseShortName && em.LicenseShortName.value) || (em.UsageTerms && em.UsageTerms.value) || "";
      const lic = licName.toLowerCase();
      const ok = /cc0|public domain/.test(lic) || (/cc.?by/.test(lic) && !/sa|nc|nd/.test(lic));
      if (!ok) continue;                                                 // licencia no usable comercialmente
      const licKey = /cc0/.test(lic) ? "cc0" : (/public domain/.test(lic) ? "public-domain" : "cc-by");
      const author = strip(em.Artist && em.Artist.value) || "Wikimedia Commons";
      const title = (p.title || "").replace(/^File:/, "");
      const page = `https://commons.wikimedia.org/wiki/${encodeURIComponent(p.title || "")}`;
      const attribution = `${title} · ${author} · Wikimedia Commons · ${licName}`;
      // Only CC-BY exige credito; CC0/PD not. Guardamos the atribucion only when is must.
      return { link: ii.url, src: "wikimedia", seek: 0, licKey, attribution: licKey === "cc-by" ? attribution : "", title, author, license: licName, page };
    }
  } catch {}
  return null;
}

// NASA (dominio public): API oficial. Resuelve the .mp4 of the item evitando ~orig (gigante):
// prefiere large/medium/small for that the descarga sea liviana.
async function nasaVideo(q) {
  try {
    const r = await tf(`https://images-api.nasa.gov/search?q=${encodeURIComponent(q)}&media_type=video&page_size=20`, 30000);
    if (!r.ok) return null;
    const s = await r.json();
    const items = (s.collection && s.collection.items) || [];
    for (const it of items) {
      try {
        const cr = await tf(it.href, 20000); if (!cr.ok) continue;
        const col = await cr.json();
        const urls = (Array.isArray(col) ? col : []).filter((u) => /\.mp4$/i.test(u));
        const pick = urls.find((u) => /~large\.mp4$/i.test(u)) || urls.find((u) => /~medium\.mp4$/i.test(u)) ||
          urls.find((u) => /~small\.mp4$/i.test(u)) || urls.find((u) => !/~orig\.mp4$/i.test(u)) || urls[0];
        if (pick) {
          const title = (it.data && it.data[0] && it.data[0].title) || q;
          const id = (it.data && it.data[0] && it.data[0].nasa_id) || "";
          // NASA = dominio public: without atribucion obligatoria (registramos the fuente igual).
          return { link: pick.replace(/^http:/, "https:"), src: "nasa", seek: 0, licKey: "public-domain", attribution: "", title, page: id ? `https://images.nasa.gov/details-${id}` : "" };
        }
      } catch {}
    }
  } catch {}
  return null;
}

// Internet Archive: licenseurl -> clave usable (rechaza SA/NC/ND) o null.
function licFromUrl(u) {
  u = (Array.isArray(u) ? u[0] : u || "").toLowerCase();
  if (/publicdomain\/zero|\/cc0/.test(u)) return "cc0";
  if (/\/by-sa|\/by-nc|\/by-nd/.test(u)) return null;
  if (/\/licenses\/by(\/|$)/.test(u)) return "cc-by";
  if (/publicdomain\/mark|\/publicdomain(\/|$)/.test(u)) return "public-domain";
  return null;
}
// Internet Archive (historico): search movies with licencia CC/PD, validates the licencia by item and
// elige the mp4/ogv MORE PEQUENO usable (derivado ligero) for download fast; makeSeg lo cuts to ~dur.
async function archiveVideo(q) {
  try {
    const cc = `(${q}) AND mediatype:(movies) AND licenseurl:(*creativecommons* OR *publicdomain*)`;
    const u = `https://archive.org/advancedsearch.php?q=${encodeURIComponent(cc)}&fl[]=identifier&fl[]=title&fl[]=licenseurl&fl[]=creator&sort[]=downloads+desc&rows=8&output=json`;
    const r = await tf(u, 30000); if (!r.ok) return null;
    const j = await r.json();
    const docs = (j.response && j.response.docs) || [];
    for (const d of docs) {
      const licKey = licFromUrl(d.licenseurl); if (!licKey) continue;    // sin licencia usable -> siguiente
      try {
        const mr = await tf(`https://archive.org/metadata/${d.identifier}`, 30000); if (!mr.ok) continue;
        const meta = await mr.json();
        const files = (meta.files || []).filter((f) => /\.(mp4|ogv)$/i.test(f.name) && +(f.size || 0) > 2e6 && +(f.size || 0) < 80e6).sort((a, b) => +a.size - +b.size);
        if (!files.length) continue;
        const f = files[0];                                              // el mas liviano usable
        const creator = (Array.isArray(d.creator) ? d.creator[0] : d.creator) || "Internet Archive";
        const title = (Array.isArray(d.title) ? d.title[0] : d.title) || q;
        const link = `https://archive.org/download/${d.identifier}/${encodeURIComponent(f.name)}`;
        const page = `https://archive.org/details/${d.identifier}`;
        const attribution = `${title} · ${creator} · ${page} · ${licKey.toUpperCase()}`;
        return { link, src: "archive", seek: 3, licKey, attribution: licKey === "cc-by" ? attribution : "", title, author: creator, license: licKey, page };
      } catch {}
    }
  } catch {}
  return null;
}

// Heuristica of respaldo (without Gemini): ¿the segmento habla of something REAL/historico/cientifico?
// -> "archival". Si es ambiente/objeto generico -> "stock".
function guessKind(text) {
  const t = (text || "").toLowerCase();
  if (/\b(1[5-9]\d{2}|20[0-2]\d)\b/.test(t)) return "archival";           // menciona un año concreto
  if (/\b(crash|depression|recession|war|president|election|founded|history|historic|ancient|century|apollo|moon|nasa|space|rocket|invented|discovered|revolution|empire|pandemic|treaty|dynasty|astronaut|satellite)\b/.test(t)) return "archival";
  return "stock";
}

// Envolturas of Pexels/Pixabay to the formato { link, src } of the ruteo.
async function pexelsSrc(q) { const l = await pexelsLink(q); return l ? { link: l, src: "pexels", seek: 0 } : null; }
async function pixabaySrc(q) { const l = await pixabayLink(q); return l ? { link: l, src: "pixabay", seek: 0 } : null; }

// RUTEO by prioridad: relevancia (file) > generico (stock) > IA.
//  - archival: Wikimedia -> Internet Archive -> NASA -> Pexels -> Pixabay
//  - stock:    Pexels -> Pixabay -> Wikimedia (by if hay something tematico)
// The first that devuelva a link usable gana; if ninguno, makeSeg cae to image IA.
async function resolveSource(kind, q) {
  const order = kind === "archival"
    ? [wikimediaVideo, archiveVideo, nasaVideo, pexelsSrc, pixabaySrc]
    : [pexelsSrc, pixabaySrc, wikimediaVideo];
  for (const fn of order) {
    try { const s = await fn(q); if (s && s.link) return s; } catch {}
  }
  return null;
}

// Gemini as "director of fotografia": elige the best shot by segmento (1 sola llamada).
async function geminiPlan(list) {
  if (!GEMINI) return null;
  const seg = list.map((s, i) => `${i + 1}) ${s.text}`).join("\n");
  // Feedback of the auditor of the intento anterior (that mejorar of the footage), if lo hay.
  const fb = (process.env.FX_FOOTAGE || "").trim()
    ? `\n\nEl auditor marco este problema de footage en el intento anterior: "${process.env.FX_FOOTAGE.trim()}". CORRIGELO: busquedas mas especificas y relevantes al tema de cada segmento, mas VARIADAS (no repitas el mismo tipo de plano) y muy cinematograficas.`
    : "";
  const prompt = `Eres director de fotografia de un video faceless cinematografico de datos/dinero (YouTube, ingles). Para CADA segmento de narracion da el MEJOR plano de fondo, PEGADO a lo que dice ese segmento.\n` +
    `Devuelve SOLO un array JSON, un objeto por segmento en el MISMO orden, con:\n` +
    `- "q" = query de 2-4 palabras en INGLES para buscar b-roll de stock. Si el segmento nombra una EMPRESA, MARCA, LUGAR, PRODUCTO u OBJETO concreto (ej: McDonald's, Tesla, stock exchange, warehouse, burger, real estate), la query DEBE ser sobre ESO especifico, no algo generico de "dinero". Usa el sustantivo concreto mas importante del segmento.\n` +
    `- "ai" = prompt de imagen IA de respaldo, tambien especifico a ese segmento.\n` +
    `- "kind" = "archival" si el segmento habla de un EVENTO, PERSONA, LUGAR o EPOCA REAL (historico, cientifico, documental: ej. crack del 29, gran depresion, Apollo 11, un presidente, una guerra, una empresa historica) -> conviene metraje de ARCHIVO real; "stock" si es un ambiente/objeto generico (dinero, oficina, ciudad, datos abstractos).\n` +
    `REGLAS: planos BRILLANTES y bien iluminados (luz de dia, evita "dark"/"night"); MUY RELEVANTES al segmento exacto; VARIADOS entre si (no repitas el mismo tipo de plano); cinematograficos. Solo cae a un plano generico de dinero/datos si el segmento no menciona nada concreto.\nSegmentos:\n${seg}${fb}`;
  for (const m of TEXT_MODELS) {
    try {
      const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent?key=${GEMINI}`, {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }], generationConfig: { responseMimeType: "application/json" } }),
      });
      if (!r.ok) { console.error(`gemini ${m}: ${r.status}`); continue; }
      const j = await r.json();
      let t = (j?.candidates?.[0]?.content?.parts?.[0]?.text || "").replace(/```json|```/g, "").trim();
      const arr = JSON.parse(t);
      if (Array.isArray(arr) && arr.length) { console.log(`Gemini (${m}) planeo ${arr.length} planos.`); return arr; }
    } catch (e) { console.error(`gemini ${m}: ${e.message}`); }
  }
  return null;
}

async function dl(url, dest) { const r = await fetch(url); fs.writeFileSync(dest, Buffer.from(await r.arrayBuffer())); }
async function aiImage(prompt, dest, seed) {
  const style = "cinematic film still, bright clean lighting, soft daylight, teal and gold grade, highly detailed, no text";
  const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt + ", " + style)}?width=1920&height=1080&nologo=true&model=flux&seed=${seed}`;
  await dl(url, dest);
}

// Generates cada shot as clip of video of the largo exacto (with movimiento real).
async function makeSeg(i, s, th, kind) {
  // +TD of "queue" for that the shot tenga with that solapar in the transition.
  const dur = Math.max(1.2, +(s.end - s.start + TD).toFixed(2));
  const out = `${outDir}/seg${String(i).padStart(3, "0")}.mp4`;
  // 1) Fuente by prioridad segun kind (file if is historico/real, stock if is generico).
  //    All the part of red va in try/catch: if something fails, is cae to the image IA of abajo.
  try {
    const got = await resolveSource(kind, th.kw);
    if (got && got.link) {
      const raw = `${outDir}/raw${i}.mp4`;
      // Archive can tener derivados something pesados -> tope more bajo; stock/wiki/nasa a little more.
      const cap = got.src === "archive" ? 80 * 1024 * 1024 : 130 * 1024 * 1024;
      const ok = await dlCapped(got.link, raw, cap, 150000);
      if (ok) {
        // seek>0 (Archive) entra to the contenido and, junto with -t dur, cuts a tramo corto (not procesa everything).
        const seekArg = got.seek ? `-ss ${got.seek}` : "";
        execSync(`ffmpeg -y -stream_loop -1 ${seekArg} -i "${raw}" -t ${dur} -vf "scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,${VF}" -an -r 30 -c:v libx264 -preset veryfast -pix_fmt yuv420p "${out}"`, { stdio: "ignore", timeout: 200000 });
        fs.rmSync(raw, { force: true });
        return { out, dur, src: got.src, licKey: got.licKey || "", attribution: got.attribution || "", meta: got };
      }
      fs.rmSync(raw, { force: true });
    }
  } catch { /* cualquier fallo de fuente -> IA */ }
  // fallback: image IA animada with zoompan (movimiento real about the image)
  const img = `${outDir}/img${i}.jpg`;
  await aiImage(th.ai, img, 1000 + i);
  const frames = Math.round(dur * 30);
  const zin = i % 2 === 0; // alterna zoom in/out
  const dir = i % 2 ? 1 : -1;
  // Zoom ALWAYS >1.1 (deja margen for panear) + PANEO diagonal -> sensacion of profundidad/camara,
  // not a zoom shot. The image is escala to 2600 for tener recorrido.
  const z = zin ? "if(lte(zoom,1.1),1.1,min(zoom+0.0010,1.32))" : "if(lte(zoom,1.1),1.32,max(1.1,zoom-0.0010))";
  const px = `iw/2-(iw/zoom/2)+(on/${frames}-0.5)*${dir * 140}`;
  const py = `ih/2-(ih/zoom/2)+(on/${frames}-0.5)*${dir * 70}`;
  execSync(`ffmpeg -y -loop 1 -i "${img}" -t ${dur} -vf "scale=2600:1463,zoompan=z='${z}':x='${px}':y='${py}':d=${frames}:s=1920x1080:fps=30,${VF}" -r 30 -c:v libx264 -preset veryfast -pix_fmt yuv420p "${out}"`, { stdio: "ignore" });
  return { out, dur, src: "ai" };
}

const plan = await geminiPlan(segs);
console.log(`Fondo tipo pelicula: ${segs.length} planos (~${SEG}s c/u) con transiciones · director: ${plan ? "Gemini" : "heuristica"}`);
const parts = [];
const durs = [];
let prevKw = null, fillerIdx = 0;
const kwCount = {};
const attributions = [];  // CC-BY que EXIGEN credito (van a la descripcion del video)
const usedSources = [];   // trazabilidad: de que fuente salio cada plano
for (let i = 0; i < segs.length; i++) {
  // Topic of the shot: Gemini if planeo, if not the heuristica.
  let th = plan && plan[i] && plan[i].q
    ? { kw: plan[i].q, ai: plan[i].ai || theme(segs[i].text).ai }
    : theme(segs[i].text);
  // kind: lo dice Gemini; if not, the heuristica about the texto of the segmento.
  let kind = plan && plan[i] && (plan[i].kind === "archival" || plan[i].kind === "stock")
    ? plan[i].kind : guessKind(segs[i].text);
  // Variedad: ningun topic dos veces seguidas NOR more of 2 veces in total.
  // To the caer to a FILLER (money/ciudad generico), the shot deja of ser "of file" -> stock.
  if (th.kw === prevKw || (kwCount[th.kw] || 0) >= 2) { th = FILLERS[fillerIdx++ % FILLERS.length]; kind = "stock"; }
  kwCount[th.kw] = (kwCount[th.kw] || 0) + 1;
  prevKw = th.kw;
  try {
    const r = await makeSeg(i, segs[i], th, kind);
    parts.push(path.resolve(r.out).replace(/\\/g, "/"));
    durs.push(r.dur);
    usedSources.push({ plano: i, source: r.src, license: r.licKey || r.src, query: th.kw, kind });
    // Acumular ONLY the CC-BY (Wikimedia/Archive) that exigen atribucion.
    if (r.licKey === "cc-by" && r.attribution) {
      const m = r.meta || {};
      attributions.push({ plano: i, source: r.src, title: m.title || "", author: m.author || "", url: m.page || "", license: m.license || "cc-by", text: r.attribution });
    }
    if (i % 5 === 0) console.log(`  ...plano ${i}/${segs.length} (${r.src}·${kind}) [${th.kw}]`);
  } catch (e) {
    console.log(`  error plano ${i}: ${e.message}`);
  }
}
// Atribuciones + trazabilidad of fuentes for the description of the video (fuera of bg.JSON,
// that NOT cambia of formato). Only CC-BY exige credito; NASA/CC0/PD/stock not.
try {
  fs.writeFileSync(`${outDir}/attributions.json`, JSON.stringify({ generated: new Date().toISOString(), credits_required: attributions, sources_used: usedSources }, null, 2));
  if (attributions.length) console.log(`Atribuciones CC-BY: ${attributions.length} -> ${outDir}/attributions.json`);
} catch {}

if (!parts.length) { console.log("Sin planos -> sin fondo."); fs.writeFileSync(`${outDir}/bg.json`, "[]"); process.exit(0); }

const bg = `${outDir}/bg.mp4`;
if (parts.length === 1) {
  execSync(`ffmpeg -y -i "${parts[0]}" -t ${total.toFixed(2)} -r 30 -c:v libx264 -preset veryfast ${SEEK_SAFE} -pix_fmt yuv420p "${bg}"`, { stdio: "inherit" });
} else {
  // Cadena of xfade: cada shot is funde with the siguiente with a transition pro.
  const inputs = parts.map((p) => `-i "${p}"`).join(" ");
  let filter = "";
  let acc = "[0:v]";
  let accLen = durs[0];
  for (let i = 1; i < parts.length; i++) {
    const offset = +(accLen - TD).toFixed(3);
    const tr = TRANS[(i - 1) % TRANS.length];
    const outLbl = `v${i}`;
    filter += `${acc}[${i}:v]xfade=transition=${tr}:duration=${TD}:offset=${offset}[${outLbl}];`;
    acc = `[${outLbl}]`;
    accLen = +(accLen + durs[i] - TD).toFixed(3);
  }
  filter = filter.replace(/;$/, "");
  execSync(`ffmpeg -y ${inputs} -filter_complex "${filter}" -map "${acc}" -t ${total.toFixed(2)} -r 30 -c:v libx264 -preset veryfast ${SEEK_SAFE} -pix_fmt yuv420p "${bg}"`, { stdio: "inherit" });
}

fs.writeFileSync(`${outDir}/bg.json`, JSON.stringify([{ start: 0, dur: +total.toFixed(2), file: bg }], null, 2));
console.log(`bg.mp4 listo: ${parts.length} planos con transiciones (${total.toFixed(1)}s).`);
